# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 08:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentupdates',
            old_name='updates_updateID',
            new_name='updates_ID',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_crisisID',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
