# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 08:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0002_auto_20171014_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='handphone_number',
            field=models.IntegerField(default=80000000, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(80000000)]),
            preserve_default=False,
        ),
    ]
