# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0003_account_handphone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentUpdates',
            new_name='CrisisUpdates',
        ),
    ]
