# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0004_auto_20171014_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisupdates',
            name='updates_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
