# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0005_crisisupdates_updates_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_crisisID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.Crisis'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_crisisID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.Crisis'),
        ),
    ]
