# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 09:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0006_auto_20171014_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisisupdates',
            name='id',
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_ID',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
