# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0007_auto_20171014_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisisupdates',
            options={'verbose_name_plural': 'Crisis Updates'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_projETAResolution',
        ),
    ]
