# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0008_auto_20171014_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='crisis_ID',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code=b'nomatch', message=b'Length has to be 4', regex=b'^\\w{4}$')]),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_ID',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code=b'nomatch', message=b'Length has to be 4', regex=b'^\\w{4}$')]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_ID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code=b'nomatch', message=b'Length has to be 8', regex=b'^\\w{8}$')]),
        ),
    ]
