# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0009_auto_20171015_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
