# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0010_plan_plan_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisupdates',
            name='updates_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
