# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0011_crisisupdates_updates_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='namey', max_length=50),
            preserve_default=False,
        ),
    ]
