# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0012_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_text', models.CharField(max_length=50)),
                ('approve_approval', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAgency',
            fields=[
                ('agency_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agency_poc', models.CharField(max_length=50)),
                ('agency_pocContact', models.CharField(max_length=50)),
                ('agency_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.Account')),
            ],
        ),
        migrations.AddField(
            model_name='approveagency',
            name='approve_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.ExternalAgency'),
        ),
        migrations.AddField(
            model_name='approveagency',
            name='approve_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_recAgencies',
            field=models.ManyToManyField(null=True, through='pmoapp.ApproveAgency', to='pmoapp.ExternalAgency'),
        ),
    ]
