# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0013_auto_20171016_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_recAgencies',
            new_name='plan_extAgencies',
        ),
    ]
