# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0014_auto_20171016_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalagency',
            name='agency_description',
            field=models.CharField(default='nata', max_length=500),
            preserve_default=False,
        ),
    ]
