# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0015_externalagency_agency_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalagency',
            options={'verbose_name_plural': 'External Agencies'},
        ),
        migrations.AddField(
            model_name='externalagency',
            name='agency_abbrev',
            field=models.CharField(default='nata', max_length=10),
            preserve_default=False,
        ),
    ]
