# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0017_auto_20171016_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalagency',
            name='agency_name',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
