# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0020_auto_20171016_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_text', models.CharField(max_length=50)),
                ('approve_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.ExternalAgency')),
                ('approve_crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.Crisis')),
            ],
            options={
                'verbose_name_plural': 'Agency Approval',
            },
        ),
        migrations.AddField(
            model_name='crisis',
            name='crisis_extAgencies',
            field=models.ManyToManyField(null=True, through='pmoapp.ApproveAgency', to='pmoapp.ExternalAgency'),
        ),
    ]
