# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0021_auto_20171016_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crisis',
            old_name='crisis_dateTime',
            new_name='crisis_datetime',
        ),
    ]
