# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0022_auto_20171018_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_approved',
            field=models.BooleanField(default=False),
        ),
    ]
