# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0023_plan_plan_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_text', models.CharField(max_length=500)),
                ('eval_planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.Plan')),
                ('eval_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoapp.Account')),
            ],
        ),
    ]
