# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0025_evalplan_eval_hascomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evalplan',
            unique_together=set([('eval_planID', 'eval_userID')]),
        ),
    ]
