# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0026_auto_20171021_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
