# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0030_auto_20171021_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalplan',
            name='eval_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
