# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0031_auto_20171021_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profilePicURL',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
