# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0032_account_profilepicurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
