# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0033_remove_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalagency',
            name='agency_abbrev',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='externalagency',
            name='agency_name',
            field=models.CharField(max_length=70),
        ),
    ]
