# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 06:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0034_auto_20171030_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCrisis',
            fields=[
                ('sc_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('crisis_ID', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('radius', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Radius(Metres)')),
            ],
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='crisis_address',
        ),
        migrations.RemoveField(
            model_name='crisisupdates',
            name='updates_ID',
        ),
        migrations.RemoveField(
            model_name='crisisupdates',
            name='updates_curRadius',
        ),
        migrations.RemoveField(
            model_name='crisisupdates',
            name='updates_curThreatLevel',
        ),
        migrations.RemoveField(
            model_name='crisisupdates',
            name='updates_text',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_approved',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_projRadius',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_submitted',
        ),
        migrations.AddField(
            model_name='crisisupdates',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crisis',
            name='crisis_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='crisis_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_crisisID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_crisisID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_status',
            field=models.CharField(max_length=25),
        ),
    ]
