# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 06:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0036_delete_crisisupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updates_crisisID', models.IntegerField()),
                ('updates_datetime', models.DateTimeField()),
                ('updates_curInjuries', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('updates_curDeaths', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('updates_curSAF', models.DecimalField(decimal_places=1, max_digits=4)),
                ('updates_curCD', models.DecimalField(decimal_places=1, max_digits=4)),
                ('updates_curSCDF', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Crisis Updates',
            },
        ),
    ]
