# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0037_crisisupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='emailAddress',
        ),
    ]
