# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0039_auto_20171031_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profilePicURL',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
