# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0040_auto_20171031_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curDeaths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curInjuries',
            field=models.IntegerField(),
        ),
    ]
