# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0041_auto_20171031_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcrisis',
            options={'verbose_name_plural': 'Sub Crisis'},
        ),
    ]
