# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0042_auto_20171031_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcrisis',
            name='crisis_type',
            field=models.CharField(default='Fire', max_length=150),
            preserve_default=False,
        ),
    ]
