# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0043_subcrisis_crisis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmyfuckingapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanID', models.CharField(blank=True, max_length=500, null=True)),
                ('Comments', models.CharField(blank=True, max_length=5000, null=True)),
                ('PlanStatus', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
