# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0044_testmyfuckingapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmyfuckingapi',
            name='PlanID',
            field=models.IntegerField(),
        ),
    ]
