# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0045_auto_20171101_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmyfuckingapi',
            name='id',
        ),
        migrations.AlterField(
            model_name='testmyfuckingapi',
            name='PlanID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
