# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0046_auto_20171102_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmyfuckingapi',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmyfuckingapi',
            name='PlanID',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
