# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0047_auto_20171102_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='testmyfuckingapi',
            name='PlanID',
            field=models.IntegerField(),
        ),
    ]
