# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0048_auto_20171102_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='planID',
            new_name='PlanID',
        ),
        migrations.AddField(
            model_name='notifications',
            name='CrisisID',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='CrisisTitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
