# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0050_auto_20171102_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_sendtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
