# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0051_plan_plan_sendtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='PlanNum',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
