# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0052_auto_20171102_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='decisionTable',
            field=models.ImageField(blank=True, upload_to=b'decisiontables'),
        ),
    ]
