# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0054_account_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcrisis',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='decisionTable',
            field=models.ImageField(blank=True, upload_to='decisiontables'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to='profilepics'),
        ),
        migrations.AlterField(
            model_name='subcrisis',
            name='radius',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Radius(Metres)'),
        ),
    ]
