# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0055_auto_20171110_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcrisis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
