# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0056_subcrisis_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='id',
        ),
        migrations.AddField(
            model_name='crisisupdates',
            name='updates_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crisis',
            name='crisis_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='crisis_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
