# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0057_auto_20171110_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crisisupdates',
            old_name='updates_curCD',
            new_name='updates_curSPF',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_CDMaximum',
            new_name='plan_SPFMaximum',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_CDRecommended',
            new_name='plan_SPFRecommended',
        ),
    ]
