# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0058_auto_20171111_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_projResolutionTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
