# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0059_auto_20171111_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_projResolutionTime',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
