# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0061_auto_20171111_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveagency',
            name='approve_text',
        ),
    ]
