# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0063_approveagency_approve_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisupdates',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSAF',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSCDF',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSPF',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SAFMaximum',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SAFRecommended',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SCDFMaximum',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SCDFRecommended',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SPFMaximum',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SPFRecommended',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_projCasualtyRate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
