# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0064_auto_20171112_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
