# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0066_auto_20171113_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
