# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0067_plan_plan_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testmyfuckingapi',
        ),
    ]
