# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0068_delete_testmyfuckingapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profilePicURL',
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='crisis_status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curDeaths',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curInjuries',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSAF',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSCDF',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSPF',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SAFMaximum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SAFRecommended',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SCDFMaximum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SCDFRecommended',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SPFMaximum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SPFRecommended',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_projCasualtyRate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_receipt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subcrisis',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subcrisis',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
