# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0069_auto_20171114_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalagency',
            name='agency_abbrev',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='externalagency',
            name='agency_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='externalagency',
            name='agency_poc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='externalagency',
            name='agency_pocContact',
            field=models.CharField(max_length=200),
        ),
    ]
