# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0070_auto_20171114_1149'),
        ('pmoapp', '0070_auto_20171114_1048'),
    ]

    operations = [
    ]
