# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmoapp', '0072_auto_20171114_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curDeaths',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curInjuries',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSAF',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSCDF',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crisisupdates',
            name='updates_curSPF',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SAFMaximum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SAFRecommended',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SCDFMaximum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SCDFRecommended',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SPFMaximum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_SPFRecommended',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_projCasualtyRate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
